### ISSUE TITLE
page doesn't have links/URLs to "this document..." itens

### ISSUE THREAD

**Issue by ribahh-4738** [AdobeDocs/commerce-operations.pt-BR#2]
Issue in ./help/implementation-playbook/project-scope/deliverables.md

URL: https://experienceleague.adobe.com/docs/commerce-operations/implementation-playbook/project-scope/deliverables.html

page doesn't have links/URLs to "this document..." itens

**Comment by KristynaVitekerova** [comment]
Obrigada pelo contato e pelo feedback, @ribahh-4738, vamos analisar o caso.

**Comment by ribahh-4738** [comment]
Olá Kristyna, obrigado pelo retorno! 

Penso que o item Business requirements

talvez aponte para https://experienceleague.adobe.com/docs/analytics-learn/tutorials/implementation/implementation-basics/creating-a-business-requirements-document.html?lang=en

Já os demais, não encontrei documentação claramente relacionada.

**Comment by KristynaVitekerova** [comment]
Agradecemos novamente pelo seu feedback, @ribahh-4738. A questão está sendo revisada e monitorada em G11N-14851.

**Comment by KristynaVitekerova** [comment]
Olá, @ribahh-4738. O proprietário da página verificou que não deve haver links. O termo “Este documento” tem o objetivo de fazer referência a um tipo de documento que os clientes podem criar. A Adobe não oferece modelos, mas vamos revisar o texto na página para esclarecer e evitar qualquer confusão. Agradecemos mais uma vez pelo seu aviso.
